// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIuaBK65aqm2YVMFh1sSMStwm2f7ss8MY',
    appId: '1:795646490074:web:88ec3ecea269aa37797ce3',
    messagingSenderId: '795646490074',
    projectId: 'kocaelispor-fan-mobil',
    authDomain: 'kocaelispor-fan-mobil.firebaseapp.com',
    storageBucket: 'kocaelispor-fan-mobil.firebasestorage.app',
    measurementId: 'G-65LLS8DD6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIL52vCDZQqgBjzi6SKnkec3udEOO3RVs',
    appId: '1:795646490074:android:f13b68ecaf64377f797ce3',
    messagingSenderId: '795646490074',
    projectId: 'kocaelispor-fan-mobil',
    storageBucket: 'kocaelispor-fan-mobil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9X1IMqHFWeEhvDiYtcnaoAuYBsSH_Q8U',
    appId: '1:795646490074:ios:f07e1dffc4c3034b797ce3',
    messagingSenderId: '795646490074',
    projectId: 'kocaelispor-fan-mobil',
    storageBucket: 'kocaelispor-fan-mobil.firebasestorage.app',
    iosBundleId: 'com.example.kocaelispor1966Mobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9X1IMqHFWeEhvDiYtcnaoAuYBsSH_Q8U',
    appId: '1:795646490074:ios:f07e1dffc4c3034b797ce3',
    messagingSenderId: '795646490074',
    projectId: 'kocaelispor-fan-mobil',
    storageBucket: 'kocaelispor-fan-mobil.firebasestorage.app',
    iosBundleId: 'com.example.kocaelispor1966Mobil',
  );
}
